GET http://localhost:5000/board/

################################
POST http://localhost:5000/board
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTM2M2JlYjUzOTkzNDk0MzMyZDQxZGIiLCJpYXQiOjE2MzEwMzM3ODZ9.tYYN8zLKx71UW5TKJOHOzTbIpKH4omJTm783lpRyh5c


{
    "title": "Board_Nam-2"
}
################################

POST http://localhost:5000/column
content-type: application/json

{
    "boardId": "6129adc4a562e04cc024d991",
    "title": "Column-2"
}

################################
PUT http://localhost:5000/column/612e435733713980347ead3d
content-type: application/json

{
    "title": "Column1-updated"
}
################################    
DELETE  http://localhost:5000/column/612e435733713980347ead3d

################################

POST http://localhost:5000/task
content-type: application/json

{
    "boardId": "6129adc4a562e04cc024d991",
    "columnId": "612e435733713980347ead3d",
    "title": "Task-3"
}

################################################################
PUT http://localhost:5000/task/612da3ca5db6824751cac696
content-type: application/json

{
    "title": "Task3-Updatedd"
}

################################
DELETE http://localhost:5000/task/612da3ca5db6824751cac696
################################
GET http://localhost:5000/board/6129adc4a562e04cc024d991

################################
Post http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "nam2", 
    "password":"nam"
}

################################
Post http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "nam1", 
    "password":"nam"
}

################################
Get http://localhost:5000/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTM2M2JlYjUzOTkzNDk0MzMyZDQxZGIiLCJpYXQiOjE2MzEyMDA5MDR9.9C6KtbkAq9WLFivF7hms1si4JBW8grUq1l262TidYn8
 