http://localhost:3000/

################################
http://localhost:3000/get


################################
POST http://localhost:3000/board
content-type: application/json

{
    "title": "Nguyen Van Nam"
}
################################

