const argon2 = require('argon2')
const express = require('express')
const router = express.Router()
const jwt = require('jsonwebtoken')
const verifyToken = require('../middleware/auth.middleware')
const authController = require('../controller/auth.controller')
const { route } = require('.')
router.post('/register', authController.createNew)
router.post('/login', authController.login)
module.exports = router
